config/routes.rb
Bestellungmanager::Application.routes.draw do
  get "pages/home"


  resources :bestellungs

  resources :gruppes

  resources :users

  resources :artikels
  get "artikels/:id/laden" => "artikels#laden", as: "laden_artikel"

  match "/auth/:provider/callback" => "sessions#create" 
  match "/signout" => "sessions#destroy", :as => :signout


   root :to => "pages#home"


end

app/models/gruppe.rb
class Gruppe < ActiveRecord::Base
    belongs_to :user
    belongs_to :artikel
    has_many :bestellungs , :dependent => :destroy
  attr_accessible  :details, :termin ,:title
  validates :title, :details, presence:true

end

app/controllers/gruppes_controller.rb
class GruppesController < ApplicationController
  load_and_authorize_resource
  before_filter :require_login!
  before_filter :require_artikel!  ,:except => [:show, :destroy, :edit, :update]

  def index
    @gruppes = current_artikel.gruppes.all

    session[:gruppe_id] = nil
  end


  def show
    if(artikel_signed_in?)
    @gruppe = current_artikel.gruppes.find(params[:id])
    else
      @gruppe = current_user.gruppes.find(params[:id])
    end

    session[:gruppe_id] = @gruppe.id

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gruppe}
      format.pdf { render :layout => false }
    end


  end


  def new
    @gruppe = current_user.gruppes.new


  end


  def edit
    if(artikel_signed_in?)
      @gruppe = current_artikel.gruppes.find(params[:id])
    else
      @gruppe = current_user.gruppes.find(params[:id])
    end
  end


  def create
    @gruppe = current_user.gruppes.new(params[:gruppe])
    @gruppe.artikel_id= current_artikel.id

      if @gruppe.save
         redirect_to @gruppe,
                     notice: 'Gruppe wurde erfolgreich erstellt.'
      else
         render action: "new"

      end

  end


  def update
      @gruppe = current_user.gruppes.find(params[:id])

      if @gruppe.update_attributes(params[:gruppe])
        if artikel_signed_in?
          redirect_to @gruppe,
                      notice: 'Gruppe wurde erfolgreich geaendert.'
        else
          redirect_to current_user
        end
      else
         render action: "edit"
      end


  end


  def destroy
    @gruppe = current_user.gruppes.find(params[:id])
    @gruppe.bestellungs.destroy_all
    @gruppe.destroy

    if(artikel_signed_in?)
      redirect_to gruppes_path,
                  notice: 'Gruppe wurde erfolgreich geloescht.'
    else
      redirect_to current_user,
                  notice: 'Gruppe wurde erfolgreich geloescht.'
    end
    end

end

app/helpers/gruppes_helper.rb
module GruppesHelper
end

app/views/gruppes/_form.html.erb
<%= form_for(@gruppe) do |f| %>


<div class="field">
	<%= f.label :title %>
	<br />
	<%= f.text_field :title %>
</div>

<div class="field">
	<%= f.label :details %>
	<br />
	<%= f.text_area :details %>
</div>

<div class="field">
	<%= f.label :termin %>
	<br />
	<%= f.text_field :termin%>
</div>
<div class="actions">
	<%= f.submit "Bestellungsgruppe erstellen" %>
</div>
<% end %>

app/views/gruppes/edit.html.erb
<h1>Bestellungsgruppe aendern</h1>

<%= render 'form' %>
<td><%= link_to 'Back', gruppes_path,:class => "btn btn-small" %></td> |
<%= link_to 'Show', @gruppe,:class => "btn btn-small btn-primary" %>

app/views/gruppes/index.html.erb
<h1>Liste der Bestellungsgruppe</h1>

<table class="table table-striped tablebordered table-condensed  ">
  <thead>
  </thead>
  <tbody>
  <tr>
    <th>Title</th>
    <th>Termin</th>
  </tr>

<% @gruppes.each do |gruppe| %>
  <tr>

    <td><%= gruppe.title %></td>
    <td><%= gruppe.termin %></td>
    <td><%= link_to 'Show', gruppe , :class => "btn btn-mini btn-info"%></td>
    <% if can? :edit, gruppe %>
    <td><%= link_to 'Edit', edit_gruppe_path(gruppe), :class => "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', gruppe, method: :delete, data: { confirm: 'Are you sure?' },
                    :class => "btn btn-mini btn-danger" %></td>
        <%end%>
  </tr>
<% end %>
</table>
<%= link_to "zur Speisekarte",current_artikel, :class => "btn btn-small" %> |
<td><%= link_to 'Neue Bestellunggruppe', new_gruppe_path, :class => "btn btn-small btn-primary" %></td>

app/views/gruppes/new.html.erb
<h1>Neue Bestellungsgruppe</h1>

<%= render 'form' %>

<%= link_to 'Back', gruppes_path,:class => "btn btn-small btn-primary"  %>

app/views/gruppes/show.html.erb
<p>
  <b>Title:</b>
  <%= @gruppe.title %>
</p>

<p>
  <b>Details:</b>
  <%= @gruppe.details %>
</p>

<p>
  <b>Termin:</b>
  <%= @gruppe.termin %>
</p>
 <p>
   <b>Summe:</b>
   <%= @gruppe.bestellungs.sum("preis")%>

 </p>
<p>
  <b>Erstellt am:</b>
  <%= @gruppe.updated_at.to_date %>
</p>
<hr>
<h2>Laufende Bestellungen für diese Gruppe</h2>
<div>
  <table  class="table table-striped tablebordered table-condensed  ">
    <tr>
      <th>Name</th>
      <th>Speise</th>
      <th>Preis</th>
      <th>Comment</th>
    </tr>

    <%@gruppe.bestellungs.each do |bestellung| %>
        <tr>
          <td><%= bestellung.name %></td>
          <td><%= bestellung.speise %></td>
          <td><%= bestellung.preis %></td>
          <td><%= bestellung.comment %></td>
        </tr>
        <% end %>
     </table>
</div>
<td><%= link_to 'zur Speisekarte', gruppes_path,:class => "btn btn-small" %></td>

<%= link_to "Gruppe Ausdruecke(PDF)" , gruppe_path(@gruppe, :format => 'pdf') ,:class => "btn btn-small btn-success"%>

<div>
    <h2>Bitte Speise Hier eingeben!!</h2>
    <%= link_to "Speise Aufnehmen", bestellungs_path,:class => "btn btn-small btn-info" %>
</div>