config/routes.rb
Bestellungmanager::Application.routes.draw do
  get "pages/home"


  resources :bestellungs

  resources :gruppes

  resources :users

  resources :artikels
  get "artikels/:id/laden" => "artikels#laden", as: "laden_artikel"

  match "/auth/:provider/callback" => "sessions#create" 
  match "/signout" => "sessions#destroy", :as => :signout


   root :to => "pages#home"


end

app/models/artikel.rb
class Artikel < ActiveRecord::Base
  belongs_to :user
  has_many :gruppes   , :dependent => :destroy

  attr_accessible :comment, :title, :image

  mount_uploader :image, ImageUploader
  validates :title, :image, presence:true
end

app/controllers/artikels_controller.rb
class ArtikelsController < ApplicationController
  before_filter :require_login!
  load_and_authorize_resource

  def index
    @artikels = Artikel.all
    session[:artikel_id] = nil
   end


  def show
    @artikel = Artikel.find(params[:id])
    session[:artikel_id] = @artikel.id
  end

  def new
    @artikel = current_user.artikels.new
  end


  def edit
    @artikel = current_user.artikels.find(params[:id])
  end


  def create
    @artikel = current_user.artikels.new(params[:artikel])

      if @artikel.save
        redirect_to @artikel,
                     notice: 'Artikel was successfully created.'
         else
         render action: "new"
      end
  end


  def update

    @artikel = current_user.artikels.find(params[:id])

      if @artikel.update_attributes(params[:artikel])
        redirect_to @artikel,
                    notice: 'Artikel was successfully updated.'

      else
        render action: "edit"
      end

  end


  def destroy
    @artikel = Artikel.find(params[:id])
    @artikel.gruppes.destroy_all
    FileUtils.rm_rf "public/uploads/artikel/image/#{@artikel.id}"
    @artikel.destroy
    redirect_to artikels_url
  end

  def laden
    send_file "public/#{Artikel.find(params[:id]).image}"

  end





end

app/helpers/artikels_helper.rb
module ArtikelsHelper
end

app/views/artikels/_form.html.erb
<%= form_for @artikel, :html => { :multipart => true} do |f| %>

  <div class="field">
    <%= f.label "Restaurant Name" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
   <div class ="field">
    <h1> <%= f.label "Hier Speisekarte hochladen" %></h1>
     <%= f.file_field 'image' %>

   </div>
  <div class="actions">
    <%= f.submit "Speisekarte erstellen" %>
  </div>
<% end %>

app/views/artikels/edit.html.erb
<h1> Speisekarte aendern</h1>

<%= render 'form' %>
<td><%= link_to 'Back', artikels_path,:class => "btn btn-small btn-info" %></td>
<%= link_to 'Show', @artikel ,:class => "btn btn-small"%> |

app/views/artikels/index.html.erb
<% if flash[:alert] %>
    <p id="alert">
      <%= flash[:alert] %>
    </p>
<% end %>

<h1>Speisekarte</h1>

<table class="table table-striped tablebordered table-condensed  ">
  <thead>
  </thead>
  <tbody>
  <tr>
    <th>Restaurant</th>

  </tr>

<% @artikels.each do |artikel| %>
  <tr>
    <td><%= artikel.title %></td>
    <td><%= link_to 'Show', artikel,:class => "btn btn-mini btn-info" %></td>
    <%  if can? :edit, artikel %>
    <td><%= link_to 'Edit', edit_artikel_path(artikel.id),:class => "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', artikel, method: :delete, data: { confirm: 'Are you sure?' },
                    :class => "btn btn-mini btn-danger" %></td>
     <% end %>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'Neue Speisekarte erstellen', new_artikel_path,:class => "btn btn-mini btn-info" %>

app/views/artikels/new.html.erb
<h1>Neue Speisekarte</h1>

<%= render 'form' %>

<%= link_to 'Back', artikels_path ,:class => "btn btn-small btn-info"%>

app/views/artikels/show.html.erb
<p>
  <b>Restaurant:</b>
  <%= @artikel.title %>
</p>
<p>
  <h2>Speisekarte</h2>
  <%=image_tag  @artikel.image.to_s ,:size => "480x400" %>
  <%= link_to "Herunterladen",laden_artikel_path,:class => "btn btn-small btn-info"  %>

</p>
<p>
  <b>Comment:</b>
  <%= @artikel.comment %>
</p>
<td><%= link_to 'Back',artikels_path,:class => "btn btn-small btn-primary" %> </td>

<%  if can? :edit, @artikel %>
<%= link_to 'Edit', edit_artikel_path(@artikel),:class => "btn btn-small" %>
    <% end %>
<div>
  <h2>Bitte hier in Gruppe anmelden!!</h2>
  <%= link_to "Bestellungsgruppe Auswaehlen", gruppes_path ,:class => "btn btn-small btn-success" %>

</div>
<div>
  <h2>Die Aktuelle Bestellungsgruppe</h2>
  <table class="table table-striped tablebordered table-condensed  ">
    <tbody>
    <tr>
      <th>Title</th>
      <th>Termin</th>
    </tr>

    <% @artikel.gruppes.each do |gruppe| %>
        <tr>
          <td><%= gruppe.title %></td>
          <td><%= gruppe.termin %></td>
        </tr>
        <% end %>
   </table>
</div>