config/routes.rb
Bestellungmanager::Application.routes.draw do
  get "pages/home"


  resources :bestellungs

  resources :gruppes

  resources :users

  resources :artikels
  get "artikels/:id/laden" => "artikels#laden", as: "laden_artikel"

  match "/auth/:provider/callback" => "sessions#create" 
  match "/signout" => "sessions#destroy", :as => :signout


   root :to => "pages#home"


end

app/models/bestellung.rb
class Bestellung < ActiveRecord::Base
   belongs_to :users
   belongs_to :gruppes
  attr_accessible  :comment, :name, :preis, :speise

  validates  :speise, :preis ,presence: true
end

app/controllers/bestellungs_controller.rb
class BestellungsController < ApplicationController
  load_and_authorize_resource
  before_filter :require_login!
  before_filter :require_gruppe! ,:except => [:show, :destroy, :edit, :update]
  def index
    @bestellungs = current_gruppe.bestellungs.all



  end

  def show
    if(sign_gruppe_in?)
    @bestellung = current_gruppe.bestellungs.find(params[:id])
    else
    @bestellung= current_user.bestellungs.find(params[:id])
     end

  end

  def new
    @bestellung = current_user.bestellungs.new

  end

  def edit
    @bestellung = current_user.bestellungs.find(params[:id])

  end

  def create
    @bestellung = current_user.bestellungs.new(params[:bestellung])
    @bestellung.name = current_user.name
    @bestellung.gruppe_id = current_gruppe.id

    if @bestellung.save
      redirect_to @bestellung, notice: 'Bestellung wurde erfolgreich erstellt'

    else
      render action: "new"
    end

  end

  def update
    @bestellung = current_user.bestellungs.find(params[:id])


    if @bestellung.update_attributes(params[:bestellung])
      if(sign_gruppe_in?)
      redirect_to @bestellung,
                     notice: 'Bestellung wurde erfolgreich geaendert.'
      else
        redirect_to current_user,
                    notice: 'Bestellung wurde erfolgreich geaendert.'
      end

    else
      render action: "edit"

    end

  end

  def destroy
    @bestellung = current_user.bestellungs.find(params[:id])
    @bestellung.destroy
    if(sign_gruppe_in?)
      redirect_to auftrags_path,
                  notice: 'Bestellung wurde erfolgreich geloescht.'
    else
      redirect_to current_user,
                  notice: 'Bestellung wurde erfolgreich geloescht.'
    end

  end

end

app/helpers/bestellungs_helper.rb
module BestellungsHelper
end

app/views/bestellungs/_form.html.erb
<div id="header">
  <% if flash[:alert] %>
      <p id="alert">
        <%= flash[:alert] %>
      </p>
  <% end %>

</div>
<%= form_for(@bestellung) do |f| %>
  <div class="field">
    <%= f.label "SpeiseNr/Name" %><br />
    <%= f.text_field :speise %>
  </div>
  <div class="field">
    <%= f.label :preis %><br />
    <%= f.number_field :preis %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit "Bestellung erstellen"%>
  </div>
<% end %>

app/views/bestellungs/edit.html.erb
<h1>Bestellung aendern!</h1>

<%= render 'form' %>

<%= link_to 'Show', @bestellung ,:class => "btn btn-small btn-info" %> |
<%= link_to 'Back', bestellungs_path,:class => "btn btn-small "  %>

app/views/bestellungs/home.html.erb
<h1>Bestellung  Manager</h1>
<% if user_signed_in? %>
    <p><%= link_to "Speisekarte", artikels_path, :class => "btn btn-small btn-info" %></p>
<% else %>
    <p><%= link_to "Einloggen", login_path, :class => "btn btn-small " %></p>
<% end %>

app/views/bestellungs/index.html.erb
<h1>Liste der Bestellungen</h1>

<table class="table table-striped tablebordered table-condensed ">
  <tr>
    <th>Name</th>
    <th>Speise</th>
    <th>Preis</th>
    <th>Comment</th>
  </tr>

<% @bestellungs.each do |bestellung| %>
  <tr>
    <td><%= bestellung.name %></td>
    <td><%= bestellung.speise %></td>
    <td><%= bestellung.preis %></td>
    <td><%= bestellung.comment %></td>
    <td><%= link_to 'Show', bestellung, :class => "btn btn-mini btn-primary" %></td>
    <% if can? :edit, bestellung %>
    <td><%= link_to 'Edit', edit_bestellung_path(bestellung), :class => "btn btn-mini " %></td>
    <td><%= link_to 'Destroy', bestellung, method: :delete, data: { confirm: 'Are you sure?' },
                    :class => "btn btn-mini btn-danger" %></td>
        <% end %>
  </tr>
<% end %>
</table>

<br />
<%= link_to "Zurueck zur Gruppe", current_gruppe, :class => "btn btn-small " %>
<td><%= link_to 'Neue Bestellung', new_bestellung_path , :class => "btn btn-small btn-primary"%></td>

app/views/bestellungs/new.html.erb
<h1>New auftrag</h1>

<%= render 'form' %>

<%= link_to 'Back', bestellungs_path,:class => "btn btn-small btn-primary" %>

app/views/bestellungs/show.html.erb
  <p>
    <b>Name</b>
    <%= @bestellung.name %>
  </p>

  <p>
    <b>Speise</b>
    <%= @bestellung.speise %>
  </p>

  <p>
    <b>Preis</b>
    <%= @bestellung.preis %>
  </p>

  <p>
    <b>Comment</b>
    <%= @bestellung.comment %>
  </p>
  <p>
    <b>Erstellt am:</b>
    <%= @bestellung.updated_at.to_date %>
  </p>


  <%= link_to 'zur Gruppe',  bestellungs_path, :class => "btn btn-small " %>
     <% if can? :edit, @bestellung %>
    <%= link_to 'Edit', edit_bestellung_path(@bestellung), :class => "btn btn-small btn-info " %>
  <%end%>