config/routes.rb
Bestellungmanager::Application.routes.draw do
  get "pages/home"


  resources :bestellungs

  resources :gruppes

  resources :users

  resources :artikels
  get "artikels/:id/laden" => "artikels#laden", as: "laden_artikel"

  match "/auth/:provider/callback" => "sessions#create" 
  match "/signout" => "sessions#destroy", :as => :signout


   root :to => "pages#home"


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bestellungmanager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div style="text-align:center;" >

  <% if user_signed_in? %>
      <%= link_to "logout", signout_path, method: :delete ,:class => "btn btn-small btn-danger"%>  |
      <td><%= link_to 'Profil', current_user,:class => "btn btn-show btn-info" %></td>  |
  <% else %>
      <%= link_to "new user", "/auth/cas", :class => "btn btn-large "%>
  <% end %>
  <% if user_signed_in? %>
      <td><%= link_to "Alle User", users_path,:class => "btn btn-small btn-info"%></td> |
      <td><%= link_to 'Speisekarte', artikels_path,:class => "btn btn-show btn-info" %></td>
  <% end %>

</div>
<div id="container">
  <div id="header">
    <% if flash[:alert] %>
        <p id="alert">
          <%= flash[:alert] %>
        </p>
    <% end %>

  </div>
    <div id="content">
     <%= yield %>
    </div>
     <div id="footer">
       @2012
     </div>
</div>
</body>
</html>